name: terminal
description: Utilities for writing tests to validate file system and Dart project directory operations.
version: 1.0.0
author: Joe Conway <joe.conway@stablekernel.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: ^1.0.0
  pubspec_parse: '>=0.1.4 <1.0.0'
  pub_cache: '>=0.2.0 <0.6.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
