name: command_line_agent
description: Utilities for writing tests to validate file system and Dart project directory operations.
version: 1.0.0-b2
author: Joe Conway <joe.conway@stablekernel.com>
homepage: https://stablekernel.com

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  pubspec: ^2.0.1

dev_dependencies:
  lint: ^1.0.0
  test: ^1.16.4
